export * from './accountPageType';
export * from './ComponentsTypes'
export * from './detailPageType';
export * from './footerType';
export * from './fundraiserPageType';
export * from './headerType';
export * from './homePageType';
export * from './landingPageType';
export * from './routes';